# This workflow is used to build the experiment and push it to github pages

name: Deploy Testing Branch

on:
  push:
    branches: 
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true

      - name: Clone ph3-lab-mgmt and build
        run: |
          git clone --depth=1 https://github.com/virtual-labs/ph3-lab-mgmt
          cd ph3-lab-mgmt
          npm install
          npm run build-exp
          cd ..

      - name: Prepare gh-pages branch
        run: |
          git config --local user.email "admin@vlabs.ac.in"
          git config --local user.name "vleadadmin"
          git checkout --orphan gh-pages
          git reset
          rm -rf plugins  # Remove conflicting directory if exists
          git add ph3-lab-mgmt/build/* -f
          git mv ph3-lab-mgmt/build/* ./ -f
          git commit -m "https://virtual-labs.github.io/${{ github.repository }} click on the link to test your code."

      - name: Push to gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ORG_OWNER_GITHUB_TOKEN }}
          force: true
          branch: gh-pages